run:
  go: "1.21"
  issues-exit-code: 1
  tests: true
  timeout: 10m
linters:
  enable:
    - unused
  disable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - gochecksumtype
    - gosec
    - gosmopolitan
    - govet
    - loggercheck
    - makezero
    - musttag
    - nilerr
    - nilnesserr
    - noctx
    - protogetter
    - reassign
    - recvcheck
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testifylint
    - unparam
    - zerologlint
  presets:
    - bugs
    - unused
  fast: false

linters-settings:
  gofmt:
    simplify: true
