[SupersonicTheme]
Name = "Aqua dark"
Version = "0.1"
SupportsDark = true
SupportsLight = false

[DarkColors]
PageBackground = "#000000"
ListHeader = "#00b4bd"
PageHeader = "#0cd7e1"
Background = "#104c4f"
ScrollBar = "#F3F3F3"
Button = "00fffb"
Foreground = "#1f5655"
InputBackground = "#14141432"

[LightColors]
PageBackground = "#FAFAFA"
ListHeader = "#E1DFE1"
PageHeader = "#e1dfe1"
Background = "#E1DFE1"
ScrollBar = "#565656"
Button = "#C8C8C8F0"
DisabledButton = "#CDCDCDF0"
Foreground = "#262626"
Hyperlink = "#3737FB"
