# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          wget
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install Dependencies
      run: pacman -Syu && pacman -S git mingw-w64-x86_64-toolchain mingw-w64-x86_64-mpv

    - name: Build
      run: go build

    - name: Install Fyne tool
      run: go install fyne.io/fyne/v2/cmd/fyne@latest
